name: Actions Android
on: [push]
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node configuration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Prepare env
      env:
        GITHUB_USER_PASSWORD: ${{ secrets.GITHUB_USER_PASSWORD }}
      run: |
        sed -i '' "s/git\+https\:\/\//https:\/\/$GITHUB_USER_PASSWORD@/g" package.json
        npm install
        cd reactnative && npm install
    - name: Build and test
      run: |
        npm install --global react-native-cli
        cd reactnative/android && ./gradlew assembleDebug